# Java Gradle
GRADLE_USER_HOME=/home/%USER%/Codespace/Language-Tooling/Gradle

# NPM
NPM_CONFIG_USERCONFIG=/home/%USER%/Codespace/Language-Tooling/.npmrc

# Rust
CARGO_HOME=/home/%USER%/Codespace/Language-Tooling/Rust/cargo
RUSTUP_HOME=/home/%USER%/Codespace/Language-Tooling/Rust/rustup
