[tools]
ruff = "latest"
pre-commit = "latest"

[tasks.setup]
description = "Set up the development environment"
run = "pre-commit install"

# Formatting ===
[tasks.lint]
description = "Report Ruff violations"
run = "ruff check ."

[tasks.format]
description = "Apply Ruff's lint fixes and formatting"
run = "ruff check --fix . && ruff format ."

# Dry Run tasks ===
[tasks.dry-run-files]
description = "Dry run Decman for file changes only (skipping checks)"
run = "NOSARCH_DECMAN_SKIP_CHECKS=1 sudo -E decman --only files --dry-run"

[tasks.dry-run-quick]
description = "Dry run Decman (skipping checks)"
run = "NOSARCH_DECMAN_SKIP_CHECKS=1 sudo -E decman --dry-run"

[tasks.apply-files]
description = "Deploy Decman file changes (skipping checks)"
run = "NOSARCH_DECMAN_SKIP_CHECKS=1 sudo -E decman --only files"
