# Managed by NosArch

# Swap Optimization
vm.swappiness=150
vm.page-cluster=0

# Memory and Cache
vm.vfs_cache_pressure=50
vm.watermark_scale_factor=125
## Watermark boosting on desktop frequently triggers false alarms, so disable it
## Doesn't actually disable all memory defragmentation, so not as harmful
vm.watermark_boost_factor=0

# Disk buffering
vm.dirty_background_bytes=67108864 # 64 MB
vm.dirty_bytes=268435456 # 256 MB
## Large unwritten data buildups already prevented by above config, so wake up less frequently
vm.dirty_writeback_centisecs=1500
