# Copied from Omarchy
# https://github.com/basecamp/omarchy/blob/9cf1852525a5f7de26d3162db9d61e2f5c1d5523/default/wireplumber/wireplumber.conf.d/bluetooth-a2dp-autoconnect.conf

## Auto-connect A2DP playback/capture profiles on Bluetooth devices.
## This helps speakers and receivers expose their audio profiles without
## requiring manual PipeWire/WirePlumber recovery.

monitor.bluez.rules = [
    {
        matches = [
            {
                device.name = "~bluez_card.*"
            }
        ]
        actions = {
            update-props = {
                bluez5.auto-connect = [ a2dp_sink a2dp_source ]
            }
        }
    }
]
