[Settings]
gtk-theme-name=Adwaita-dark
gtk-application-prefer-dark-theme=1

[AdwStyleManager]
color-scheme=ADW_COLOR_SCHEME_FORCE_DARK
#https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/property.StyleManager.color-scheme.html
