# Background and foreground colors
background = #%BACKGROUND_TERTIARY%
foreground = #%FOREGROUND_PRIMARY%

# Standard colors
palette = 0=#%ANSI_COLOR_0%
palette = 1=#%ANSI_COLOR_1%
palette = 2=#%ANSI_COLOR_2%
palette = 3=#%ANSI_COLOR_3%
palette = 4=#%ANSI_COLOR_4%
palette = 5=#%ANSI_COLOR_5%
palette = 6=#%ANSI_COLOR_6%
palette = 7=#%ANSI_COLOR_7%

# Bright colors
palette = 8=#%ANSI_COLOR_8%
palette = 9=#%ANSI_COLOR_9%
palette = 10=#%ANSI_COLOR_10%
palette = 11=#%ANSI_COLOR_11%
palette = 12=#%ANSI_COLOR_12%
palette = 13=#%ANSI_COLOR_13%
palette = 14=#%ANSI_COLOR_14%
palette = 15=#%ANSI_COLOR_15%
