# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#%BACKGROUND%"

# Main text color
theme[main_fg]="#%FOREGROUND%"

# Title color for boxes
theme[title]="#%FOREGROUND%"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#%ACCENT%"

# Background color of selected item in processes box
theme[selected_bg]="#%SELECTION_BG%"

# Foreground color of selected item in processes box
theme[selected_fg]="#%SELECTION_FG%"

# Color of inactive/disabled text
theme[inactive_fg]="#%COLOR8%"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#%BTOP_GRAPH_TEXT%"

# Background color of the percentage meters
theme[meter_bg]="#%FOREGROUND%"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#%COLOR15%"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#%COLOR5%"
theme[mem_box]="#%COLOR2%"
theme[net_box]="#%COLOR1%"
theme[proc_box]="#%COLOR4%"

# Box divider line and small boxes line color
theme[div_line]="#%COLOR8%"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#%COLOR2%"
theme[temp_mid]="#%COLOR3%"
theme[temp_end]="#%COLOR1%"

# CPU graph colors (Teal -> Blue -> Purple)
theme[cpu_start]="#%COLOR6%"
theme[cpu_mid]="#%COLOR4%"
theme[cpu_end]="#%COLOR5%"

# Mem/Disk free meter
theme[free_start]="#%COLOR5%"
theme[free_mid]="#%COLOR4%"
theme[free_end]="#%COLOR6%"

# Mem/Disk cached meter
theme[cached_start]="#%COLOR4%"
theme[cached_mid]="#%COLOR6%"
theme[cached_end]="#%COLOR5%"

# Mem/Disk available meter
theme[available_start]="#%COLOR3%"
theme[available_mid]="#%COLOR1%"
theme[available_end]="#%COLOR1%"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#%COLOR2%"
theme[used_mid]="#%COLOR6%"
theme[used_end]="#%COLOR4%"

# Download graph colors
theme[download_start]="#%COLOR3%"
theme[download_mid]="#%COLOR1%"
theme[download_end]="#%COLOR1%"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#%COLOR2%"
theme[upload_mid]="#%COLOR6%"
theme[upload_end]="#%COLOR4%"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#%COLOR6%"
theme[process_mid]="#%COLOR4%"
theme[process_end]="#%COLOR5%"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#%COLOR0%"
theme[gradient_color_1]="#%BTOP_GRADIENT_1%"
theme[gradient_color_2]="#%COLOR7%"
theme[gradient_color_3]="#%COLOR8%"
theme[gradient_color_4]="#%BTOP_GRADIENT_4%"
theme[gradient_color_5]="#%COLOR7%"
theme[gradient_color_6]="#%COLOR15%"
theme[gradient_color_7]="#%BTOP_GRADIENT_7%"
