# For setting the default editor
EDITOR=zeditor

# For setting the default graphical editor
VISUAL=zeditor

# For allowing to talk to podman from docker socket
DOCKER_HOST=unix:$XDG_RUNTIME_DIR/podman/podman.sock

# Mise-en-place settings
MISE_DATA_DIR=/home/%USER%/Codespace/Language-Tooling/mise

# Language-specific variables

# Rust
CARGO_HOME=/home/%USER%/Codespace/Language-Tooling/Rust/cargo
RUSTUP_HOME=/home/%USER%/Codespace/Language-Tooling/Rust/rustup

# Java
MAVEN_USER_HOME=/home/%USER%/Codespace/Language-Tooling/Maven
