# For setting the default editor
EDITOR=zeditor

# For setting the default graphical editor
VISUAL=zeditor

# For allowing to talk to podman from docker socket
DOCKER_HOST=unix:$XDG_RUNTIME_DIR/podman/podman.sock
