$font = JetBrainsMono Nerd Font
$background_color = rgba(3584E433)
$inner_color = rgba(1D1D20A8)
$outer_color = rgba(3584E4FF)
$font_color = rgba(FFFFFFFF)
$check_color = rgba(9A9A9CFF)
$fail_color = rgba(FF6666FF)

general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 1500 # 1.5 seconds
}

auth {
    fingerprint:enabled = false
}

background {
    monitor =
    color = $background_color
    path = ~/.local/share/current-theme/current-background.jpg
    blur_passes = 2
}

animations {
    enabled = true
    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, linear
}

input-field {
    monitor =
    size = 300, 50
    position = 0, 100
    halign = center
    valign = bottom

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4
    font_family = $font
    font_color = $font_color
    check_color = $check_color
    fail_color = $fail_color
    rounding = 10
    shadow_passes = 0

    placeholder_text = Enter Password
    check_text = Authenticating...
    fail_text = $FAIL ($ATTEMPTS)

    fade_on_empty = false
}

# User Icon
label {
    text = <span>  </span>

    monitor =
    position = -8, 200
    halign = center
    valign = bottom

    font_family = $font
    font_size = 35
    color = $font_color
}

# Username
label {
    text = $USER

    monitor =
    position = 0, 165
    halign = center
    valign = bottom

    font_family = $font
    font_size = 15
    color = $font_color
}

# Date
label {
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds

    monitor =
    position = 0, -185
    halign = center
    valign = top

    font_family = $font
    font_size = 13
    color = $font_color
}

# Time
label {
    text = $TIME12

    monitor =
    position = 0, -100
    halign = center
    valign = top

    font_family = $font
    font_size = 50
    color = $font_color
}

# Battery indicator
label {
    text = cmd[update:20000] echo -e "󰁹 $(cat /sys/class/power_supply/BAT*/capacity)%"

    monitor =
    position = -30, -30
    halign = right
    valign = top

    font_family = $font
    font_size = 10
    color = $font_color

    shadow_passes = 0
}
